name: Deploy to VPS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/
            if [ -d "leaf-to-leaf/.git" ]; then
              cd leaf-to-leaf
              git fetch --all
              git reset --hard origin/main
              git clean -fd
            else
              rm -rf leaf-to-leaf
              git clone git@github.com:${{ github.repository }}.git leaf-to-leaf
              cd leaf-to-leaf
            fi
            docker-compose down --remove-orphans
            docker-compose build --no-cache
            docker-compose up -d 