name: Deploy to VPS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/
            if [ -d "nextjs-app/.git" ]; then
              cd nextjs-app
              git fetch --all
              git reset --hard origin/main
              git clean -fd
            else
              rm -rf nextjs-app
              git clone git@github.com:${{ github.repository }}.git nextjs-app
              cd nextjs-app
            fi
            docker-compose down --remove-orphans
            docker-compose build --no-cache
            docker-compose up -d 